owner: tkuennen
repo: uptime
sites:
  - name: www.traviskuennen.com (Landing)
    url: https://www.traviskuennen.com
  - name: til.traviskuennen.com (Today I learned)
    url: https://til.traviskuennen.com
assignees:
  - tkuennen
user-agent: tkuennen
commitMessages:
  commitAuthorName: "Travis Bot"
  commitAuthorEmail: "tkuennen@ieee.org"
status-website:
  publish: true
  theme: night
  apiBaseUrl: https://api.github.com
  cname: uptime.traviskuennen.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/tkuennen/uptime
    - title: Landing
      href: https://www.traviskuennen.com
    - title: TIL
      href: https://til.traviskuennen.com
