owner: tkuennen
repo: uptime
runner: "[self-hosted, linux, X64]"
sites:
  - name: www.traviskuennen.com (Landing)
    url: https://www.traviskuennen.com
  - name: til.traviskuennen.com (Today I learned)
    url: https://til.traviskuennen.com
  - name: jokes.traviskuennen.com
    url: https://jokes.traviskuennen.com
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: HOME
    url: https://home.in.kuennen.net
  - name: Cloud
    url: https://cloud.in.kuennen.net  
assignees:
  - tkuennen
user-agent: tkuennen
commitMessages:
  commitAuthorName: "Travis Bot"
  commitAuthorEmail: "tkuennen@ieee.org"
status-website:
  publish: true
  theme: night
  apiBaseUrl: https://api.github.com
  cname: uptime.traviskuennen.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/tkuennen/uptime
    - title: Landing
      href: https://www.traviskuennen.com
    - title: TIL
      href: https://til.traviskuennen.com
    - title: Jokes
      href: https://jokes.traviskuennen.com
